name: Build, Deploy, and Commit JavaFX App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Deploy, and Commit JavaFX App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to enable commits

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Download JavaFX SDK
        run: curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/21.0.1/openjfx-21.0.1_linux-x64_bin-sdk.zip

      - name: Unzip JavaFX SDK
        run: unzip javafx-sdk.zip

      - name: Set JavaFX path
        run: echo "PATH_TO_FX=$(pwd)/javafx-sdk-21.0.1/lib" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package

      - name: Create Executables Directory
        run: mkdir -p executables

      - name: Move Jar to Executables
        run: |
          mv target/*.jar executables/
        working-directory: . # Adjust for Maven's output directory

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Executables
        run: |
          git add executables/
          git commit -m "Add built artifact to executables folder [skip ci]"
          git push

      - name: Run Application with Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          java --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml -jar executables/AdventCalender-1.0-SNAPSHOT.jar
