name: Build, Deploy, and Commit JavaFX App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Deploy, and Commit JavaFX App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to enable commits

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: |
          mvn clean package
        working-directory: . # Adjust if your `pom.xml` is in a subdirectory

      - name: Create Executables Directory
        run: mkdir -p executables

      - name: Move Jar to Executables
        run: |
          mv target/*.jar executables/
        working-directory: . # Adjust for Maven's output directory

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit Executables
        run: |
          git add executables/
          git commit -m "Add built artifact to executables folder [skip ci]"
          git push